In [2]:
import numpy as np 

## Arrays 

Attributes - size, shape, memory sunption and data types 
Indexing - getting and setting value of individual array elements 
Slicing - Getting and setting subarrays within a larger array 
Reshaping - Shanging shape of array 
Joining and splitting - combining multiple arrays into one and splitting one array into many 

#### Attributes 

In [ ]:
x1 = np.random.randint(10, size=6) # 1D array 
x2 = np.random.randint(10, size=(3, 4)) # 2D array 
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array 

In [6]:
# Each array has these attributes: 
# ndim = number of dimensions 
# shape = size of each dimension 
# size = total size of the array (a x b x c x ....)

print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)
print("dtype:", x3.dtype)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60
dtype: int32


In [ ]:
# itemsize = size in bytes for each array element 
# nbytes = list total size in bytes of the array : itemsize x size 
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


#### Indexing 

In [8]:
x1

array([0, 7, 8, 2, 4, 9], dtype=int32)

In [9]:
x1[0]

np.int32(0)

In [10]:
x1[-1]

np.int32(9)

In [12]:
x2

array([[4, 0, 4, 3],
       [5, 3, 6, 0],
       [8, 2, 8, 1]], dtype=int32)

In [13]:
x2[0, 0]

np.int32(4)

In [14]:
x2[2, -1]

np.int32(1)

In [ ]:
x2[0, 0] = 12 
x2

array([[12,  0,  4,  3],
       [ 5,  3,  6,  0],
       [ 8,  2,  8,  1]], dtype=int32)

In [18]:
# Have fixed types unlike python lists therefore have to modify with 
# the same dtype e.g. try to add flop to an int results in silently truncated value
x1[0] = 3.14159
x1

array([3, 7, 8, 2, 4, 9], dtype=int32)

#### Slicing 

##### 1D arrays 

In [ ]:
# data[start:stop:step] - indexes start from 0 
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[4:7]

array([4, 5, 6])

In [26]:
x[1::2] # Every other element starting from the 1st index 

array([1, 3, 5, 7, 9])

In [27]:
x[::-1] # Reversing an array 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[5::-2]

array([5, 3, 1])

##### Multi-D arrays 

In [29]:
x2

array([[12,  0,  4,  3],
       [ 5,  3,  6,  0],
       [ 8,  2,  8,  1]], dtype=int32)

In [ ]:
x2[:2, :3] # Return the first two rows and the first three columns of each row

array([[12,  0,  4],
       [ 5,  3,  6]], dtype=int32)

In [32]:
x2[:3, ::2] # Return the first 3 rows and take 2 steps per column 
# starting from the first column 

array([[12,  4],
       [ 5,  6],
       [ 8,  8]], dtype=int32)

In [34]:
x2[::-1, ::-1] # Take all the rows and make the bottom row the first row 
# Then take ann the elemnts from each column and reverse their index position 

array([[ 1,  8,  2,  8],
       [ 0,  6,  3,  5],
       [ 3,  4,  0, 12]], dtype=int32)

##### Accessing array rows and columns 

In [36]:
print(x2[:, 0]) # Go across the whole array and print the first column

[12  5  8]


In [39]:
print(x2[0, :]) # Print first row 
print(x2[0]) # Equivalent 

[12  0  4  3]
[12  0  4  3]


##### Subarrays 

In [ ]:
# Python list slicing = copies 
# Numpy slicing = modifies original array thf for bigger arrays can access data 
# w/o needing to copy them
x2

array([[12,  0,  4,  3],
       [ 5,  3,  6,  0],
       [ 8,  2,  8,  1]], dtype=int32)

In [42]:
x2_sub_array = x2[:2, :2]
x2_sub_array

array([[12,  0],
       [ 5,  3]], dtype=int32)

In [43]:
x2_sub_array[0, 0] = 99
x2_sub_array

array([[99,  0],
       [ 5,  3]], dtype=int32)

In [44]:
x2_sub_array

array([[99,  0],
       [ 5,  3]], dtype=int32)

##### Creating copies of arrays 

In [46]:
x2_sub_array_copy = x2[:2, :2].copy()
x2_sub_array_copy

array([[99,  0],
       [ 5,  3]], dtype=int32)

In [47]:
x2_sub_array_copy[0, 0] = 42 
x2_sub_array_copy

array([[42,  0],
       [ 5,  3]], dtype=int32)

#### Reshaping 

In [49]:
shaped_grid = np.arange(1, 10)
shaped_grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
grid
# The size of the shaped grid needs to match the dimensions that it wants to be 
# reshaped into e.g. there are 9 elements in 1-9 and to reshape into 3 x 3 
# is 9 elements 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# Converting 1D array to 2D row 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [55]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [56]:
# Reshape row via newaxis 
x[np.newaxis, :]

array([[1, 2, 3]])

In [57]:
# Converting 1D array to 2D column 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [58]:
# Reshaping column via newaxis 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### Concatenation 

In [59]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [60]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [62]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Concatenate on the second axis (zero-indexed) - aka concatenate on columns 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# Vertical stack - have to have the same number of columns 
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Horizontal stack - have to have the same number of rows 
y = np.array([[99], 
              [99]])
np.hstack([y, grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [ ]:
# Stack on 3rd axis - each row of both objs become cols
z = np.array([[99, 99, 99], 
              [99, 99, 99]])
np.dstack([z, grid])

array([[[99,  1],
        [99,  2],
        [99,  3]],

       [[99,  4],
        [99,  5],
        [99,  6]]])

#### Splitting 

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # split at index 3 and 5
print(x1, x2, x3)
# N split-points, leads to N + 1 subarrays

[1 2 3] [99 99] [3 2 1]


In [71]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
upper, lower = np.vsplit(grid, [2])
print(f"Upper: {upper}")
print(f"Lower: {lower}")

Upper: [[0 1 2 3]
 [4 5 6 7]]
Lower: [[ 8  9 10 11]
 [12 13 14 15]]


In [74]:
left, right = np.hsplit(grid, [2])
print(f"Left: {left}")
print(f"Right: {right}")

Left: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [101]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [102]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [103]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]),
 array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]),
 array([], shape=(2, 2, 0), dtype=float64)]

In [100]:
grid.size
grid.ndim

2